vich_uploader:
    db_driver: orm

    mappings:
        users:
            uri_prefix: /uploads/user_profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/user_profile_pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
